//! Zendesk webhook signature verification.
//!
//! Scheme, per Zendesk's official documentation
//! (<https://developer.zendesk.com/documentation/webhooks/verifying>
//! "Verifying webhook authenticity"), the request-header reference on
//! <https://developer.zendesk.com/documentation/webhooks/anatomy-of-a-webhook-request>,
//! and the Node reference implementation shipped on the verifying page:
//!
//! - Headers: `X-Zendesk-Webhook-Signature`,
//!   `X-Zendesk-Webhook-Signature-Timestamp` (RFC 3339, e.g.
//!   `2021-03-25T05:09:27Z`).
//! - Signed string: `"{timestamp}{raw_body}"` — the timestamp **exactly as it
//!   appears in its header** (concatenated with the raw body bytes; no
//!   separators). Represented simply in the docs as
//!   `base64(HMACSHA256(TIMESTAMP + BODY))`; the numeric grammar of the
//!   timestamp must never be re-serialized into the signed bytes — the verbatim
//!   header substring is what was signed.
//! - Algorithm: HMAC-SHA256, **base64**-encoded (standard alphabet, padded),
//!   carried bare in the header (no `sha256=` prefix). Key: the webhook's
//!   signing secret as its UTF-8 string bytes, **not** base64-decoded — the
//!   docs' reference code keys the HMAC with the secret string verbatim
//!   (`crypto.createHmac("sha256", SIGNING_SECRET)`). The signing secret is
//!   generated by Zendesk ("Reveal secret" on the webhook, or
//!   `GET /api/v2/webhooks/{id}/signing_secret`) and is opaque bytes from this
//!   crate's perspective; test webhooks created by Zendesk's docs use the
//!   static secret `dGhpc19zZWNyZXRfaXNfZm9yX3Rlc3Rpbmdfb25seQ==`.
//!
//! # Replay protection
//!
//! Zendesk signs a timestamp, enabling symmetric replay protection. The signed
//! timestamp is compared symmetrically (`|now - t|`) against
//! [`VerifyOptions::max_age`] (default 300s) using `now` from the injected
//! clock. Zendesk's docs do not prescribe a freshness window (only the checksum
//! comparison is demonstrated); applying the shared window here is strictly
//! stronger than their sample code and cannot reject a legitimate delivery the
//! provider considers valid (the timestamp is HMAC-covered, so an attacker
//! cannot freshen it).

#![deny(clippy::unwrap_used, clippy::expect_used)]

use alloc::vec::Vec;

use crate::core::VerifyOptions;
use crate::core::crypto::verify_hmac_sha256;
use crate::core::error::VerifyError;
use crate::core::headers::HeaderMap;
use crate::core::replay::{check_replay, parse_rfc3339_timestamp};
use crate::core::secret::Secret;
use base64::Engine;

/// The header carrying Zendesk's signature.
pub(crate) const SIGNATURE_HEADER: &str = "X-Zendesk-Webhook-Signature";

/// The header carrying the signed RFC 3339 webhook timestamp.
pub(crate) const TIMESTAMP_HEADER: &str = "X-Zendesk-Webhook-Signature-Timestamp";

/// HMAC-SHA256 output length in bytes.
const SIGNATURE_LEN_BYTES: usize = 32;

pub(crate) fn verify(
    headers: &dyn HeaderMap,
    raw_body: &[u8],
    secret: &Secret,
    options: &VerifyOptions,
) -> Result<(), VerifyError> {
    let signature_value = headers
        .get(SIGNATURE_HEADER)
        .ok_or(VerifyError::MissingHeader {
            header: SIGNATURE_HEADER,
        })?;
    let timestamp_raw = headers
        .get(TIMESTAMP_HEADER)
        .ok_or(VerifyError::MissingHeader {
            header: TIMESTAMP_HEADER,
        })?;

    let provided_signature = parse_signature(signature_value)?;
    let timestamp = parse_rfc3339_timestamp(TIMESTAMP_HEADER, timestamp_raw)?;

    // Signed string is `{timestamp_as_sent}{raw_body}`; the timestamp substring
    // is reused verbatim so whatever was actually signed is what gets verified
    // (Zendesk's docs: `base64(HMACSHA256(TIMESTAMP + BODY))`).
    let mut signed_string = Vec::with_capacity(timestamp_raw.len() + raw_body.len());
    signed_string.extend_from_slice(timestamp_raw.as_bytes());
    signed_string.extend_from_slice(raw_body);

    if !verify_hmac_sha256(secret.as_bytes(), &signed_string, &provided_signature) {
        return Err(VerifyError::SignatureMismatch);
    }

    check_replay(timestamp, options)
}

/// Parses `X-Zendesk-Webhook-Signature` into its 32 decoded signature bytes.
///
/// The value carries no `sha256=` prefix — it is bare base64. Every failure
/// mode maps to a distinct error variant so callers can tell malformed-request
/// noise from signature-mismatch signals (`spec.md` §2.1).
fn parse_signature(value: &str) -> Result<Vec<u8>, VerifyError> {
    if value.is_empty() {
        return Err(VerifyError::MalformedHeader {
            header: SIGNATURE_HEADER,
            reason: "header is empty",
        });
    }

    let bytes = base64::engine::general_purpose::STANDARD
        .decode(value)
        .map_err(|_| VerifyError::BadEncoding {
            reason: "signature is not valid standard base64",
        })?;

    if bytes.len() != SIGNATURE_LEN_BYTES {
        return Err(VerifyError::BadEncoding {
            reason: "signature does not decode to 32 bytes",
        });
    }

    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::{SIGNATURE_HEADER, TIMESTAMP_HEADER};
    use crate::core::error::VerifyError;
    use crate::core::options::VerifyOptions;
    use crate::core::secret::Secret;
    use crate::test_helpers::clocked_at;
    #[cfg(not(feature = "std"))]
    use crate::test_helpers::*;
    use crate::verify;
    use std::time::Duration;

    /// Zendesk's published static signing secret for test webhooks, quoted
    /// verbatim from the docs
    /// (<https://developer.zendesk.com/documentation/webhooks/verifying>:
    /// "The static secret for verifying a test webhook before it is created
    /// will always be ..."). It is used here as the HMAC key **verbatim** (its
    /// literal UTF-8 bytes) — the docs' Node reference code keys the HMAC with
    /// this string directly and never base64-decodes the secret. If the crate
    /// were to decode it first, the vectors below would not verify.
    const SECRET: &str = "dGhpc19zZWNyZXRfaXNfZm9yX3Rlc3Rpbmdfb25seQ==";
    /// The example timestamp Zendesk's own request-anatomy docs publish
    /// (<https://developer.zendesk.com/documentation/webhooks/anatomy-of-a-webhook-request>),
    /// matching unix seconds `1616648967`.
    const TIMESTAMP: &str = "2021-03-25T05:09:27Z";
    /// A `zen:event-type:ticket.created` delivery shaped like the examples in
    /// Zendesk's docs (the anatomy page's `x-zendesk-webhook-id` is reused).
    const BODY: &[u8] = b"{\"zen:event-type\":\"zen:event-type:ticket.created\",\"webhook_id\":\"01F1KRFQ6BG29CNWFR60NK5FNY\",\"account_id\":\"123456\",\"ticket\":{\"id\":61241563692,\"subject\":\"Customer inquiry\",\"status\":\"new\"}}";
    /// Locally constructed over the concatenation `TIMESTAMP + BODY`
    /// (Zendesk's documented `base64(HMACSHA256(TIMESTAMP + BODY))`), because
    /// Zendesk publishes no byte-exact example signature in its docs:
    /// `printf '%s' "$TIMESTAMP$BODY..." | openssl dgst -sha256 -hmac "<SECRET>" -binary | base64`,
    /// cross-checked with Python's `hmac` module.
    const SIGNATURE: &str = "AIKe20cG9E5XJyLFwhJV65AB0VqYImb600SJaS0Q5kI=";
    /// Locally constructed over `TIMESTAMP` alone — the docs note not all
    /// webhook requests carry a body (`GET`s/`DELETE`s use an empty body), so
    /// `base64(HMACSHA256(TIMESTAMP))` must verify too (boundary case).
    const EMPTY_BODY_SIGNATURE: &str = "wCdBvXaHttn0wRVIYctzZ9O6O0bnqWakJMEKZ9VoRWw=";
    /// Locally constructed over `TIMESTAMP + "héllo, 🦀 world!"` (unicode
    /// boundary case).
    const UNICODE_BODY_SIGNATURE: &str = "77WjbET/ibkkMCdEeAk1DcTAgiyWxGSO1hr123Cuu/Q=";

    fn zendesk_headers(signature: &str, timestamp: &str) -> Vec<(String, String)> {
        vec![
            (SIGNATURE_HEADER.to_string(), signature.to_string()),
            (TIMESTAMP_HEADER.to_string(), timestamp.to_string()),
        ]
    }

    fn verify_with(
        body: &[u8],
        signature: &str,
        timestamp: &str,
        options: VerifyOptions,
    ) -> Result<(), VerifyError> {
        verify(
            crate::Provider::Zendesk,
            &zendesk_headers(signature, timestamp),
            body,
            &Secret::new(SECRET),
            options,
        )
    }

    fn verify_fresh(body: &[u8], signature: &str) -> Result<(), VerifyError> {
        verify_with(
            body,
            signature,
            TIMESTAMP,
            clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
        )
    }

    #[test]
    fn constructed_vector_verifies() {
        assert_eq!(verify_fresh(BODY, SIGNATURE), Ok(()));
    }

    #[test]
    fn boundary_bodies_verify() {
        assert_eq!(verify_fresh(b"", EMPTY_BODY_SIGNATURE), Ok(()));
        assert_eq!(
            verify_fresh("héllo, 🦀 world!".as_bytes(), UNICODE_BODY_SIGNATURE),
            Ok(())
        );
    }

    #[test]
    fn header_names_are_case_insensitive() {
        let result = verify(
            crate::Provider::Zendesk,
            &[
                (
                    "x-zendesk-webhook-signature",
                    SIGNATURE.to_string().as_str(),
                ),
                (
                    "x-zendesk-webhook-signature-timestamp",
                    TIMESTAMP.to_string().as_str(),
                ),
            ],
            BODY,
            &Secret::new(SECRET),
            clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
        );
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn negative_flipped_signature_byte_fails() {
        // Flip one character *within* the base64 so this exercises a
        // wrong-but-well-formed signature, not a decoding failure.
        let flipped = format!("{}B{}", &SIGNATURE[..3], &SIGNATURE[4..]);
        assert_ne!(flipped, SIGNATURE);
        assert_eq!(
            verify_fresh(BODY, &flipped),
            Err(VerifyError::SignatureMismatch)
        );
    }

    #[test]
    fn tampered_body_fails() {
        let tampered = b"{\"zen:event-type\":\"zen:event-type:ticket.created\",\"webhook_id\":\"01F1KRFQ6BG29CNWFR60NK5FNY\",\"account_id\":\"123456\",\"ticket\":{\"id\":61241563692,\"subject\":\"Customer inquiry\",\"status\":\"open\"}}";
        assert_eq!(
            verify_fresh(tampered, SIGNATURE),
            Err(VerifyError::SignatureMismatch)
        );
    }

    #[test]
    fn tampered_timestamp_spelling_fails_signature_check() {
        // The timestamp is signed verbatim: altering its spelling (here,
        // adding fractional seconds) changes the signed string even though it
        // still denotes the same instant.
        let result = verify_with(
            BODY,
            SIGNATURE,
            "2021-03-25T05:09:27.000Z",
            clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
        );
        assert_eq!(result, Err(VerifyError::SignatureMismatch));
    }

    #[test]
    fn wrong_secret_fails() {
        // A different secret must not verify — and importantly, the secret is
        // used verbatim, not base64-decoded, so the vector's key matters.
        let result = verify(
            crate::Provider::Zendesk,
            &zendesk_headers(SIGNATURE, TIMESTAMP),
            BODY,
            &Secret::new("cf0ea69e5eb34cbba2db17a22a1b41c3"),
            clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
        );
        assert_eq!(result, Err(VerifyError::SignatureMismatch));
    }

    #[test]
    fn replay_old_timestamp_out_of_tolerance() {
        let options = clocked_at(1_616_648_967 + 301, Some(Duration::from_secs(300)));
        let result = verify_with(BODY, SIGNATURE, TIMESTAMP, options);
        assert_eq!(
            result,
            Err(VerifyError::TimestampOutOfTolerance {
                skew: Duration::from_secs(301),
                max_age: Duration::from_secs(300),
            })
        );
    }

    #[test]
    fn replay_future_timestamp_out_of_tolerance() {
        let options = clocked_at(1_616_648_967 - 301, Some(Duration::from_secs(300)));
        let result = verify_with(BODY, SIGNATURE, TIMESTAMP, options);
        assert_eq!(
            result,
            Err(VerifyError::TimestampOutOfTolerance {
                skew: Duration::from_secs(301),
                max_age: Duration::from_secs(300),
            })
        );
    }

    #[test]
    fn replay_within_tolerance_verifies_at_window_edges() {
        for now in [1_616_648_967 - 300, 1_616_648_967 + 300] {
            let result = verify_with(
                BODY,
                SIGNATURE,
                TIMESTAMP,
                clocked_at(now, Some(Duration::from_secs(300))),
            );
            assert_eq!(result, Ok(()), "now = {now}");
        }
    }

    #[test]
    fn disabled_max_age_accepts_stale_signatures() {
        let result = verify_with(
            BODY,
            SIGNATURE,
            TIMESTAMP,
            clocked_at(1_616_648_967 + 86_400 * 365, None),
        );
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn missing_headers_error_distinctly() {
        let missing_signature = verify(
            crate::Provider::Zendesk,
            &[(TIMESTAMP_HEADER, TIMESTAMP.to_string().as_str())],
            BODY,
            &Secret::new(SECRET),
            Default::default(),
        );
        assert_eq!(
            missing_signature,
            Err(VerifyError::MissingHeader {
                header: SIGNATURE_HEADER
            })
        );

        let missing_timestamp = verify(
            crate::Provider::Zendesk,
            &[(SIGNATURE_HEADER, SIGNATURE.to_string().as_str())],
            BODY,
            &Secret::new(SECRET),
            Default::default(),
        );
        assert_eq!(
            missing_timestamp,
            Err(VerifyError::MissingHeader {
                header: TIMESTAMP_HEADER
            })
        );

        let all_missing = verify(
            crate::Provider::Zendesk,
            &Vec::<(String, String)>::new(),
            BODY,
            &Secret::new(SECRET),
            Default::default(),
        );
        assert_eq!(
            all_missing,
            Err(VerifyError::MissingHeader {
                header: SIGNATURE_HEADER
            })
        );
    }

    #[test]
    fn malformed_signature_header_errors_distinctly() {
        let cases: Vec<(String, VerifyError)> = vec![
            (
                String::new(),
                VerifyError::MalformedHeader {
                    header: SIGNATURE_HEADER,
                    reason: "header is empty",
                },
            ),
            // Garbage value: not valid base64.
            (
                "not base64!!".to_string(),
                VerifyError::BadEncoding {
                    reason: "signature is not valid standard base64",
                },
            ),
            // Valid base64 alphabet but wrong decoded length (SHA-1 size).
            (
                "2jmj7l5rSw0yVb/vlWAYkK/YBwk=".to_string(),
                VerifyError::BadEncoding {
                    reason: "signature does not decode to 32 bytes",
                },
            ),
            // Missing padding: the same 32 bytes without the trailing `=`
            // must be rejected, matching Xero/Shopify's base64 behavior.
            (
                SIGNATURE[..SIGNATURE.len() - 1].to_string(),
                VerifyError::BadEncoding {
                    reason: "signature is not valid standard base64",
                },
            ),
        ];
        for (value, expected) in cases {
            let result = verify_with(
                BODY,
                &value,
                TIMESTAMP,
                clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
            );
            assert_eq!(result, Err(expected), "input: {value:?}");
        }
    }

    #[test]
    fn malformed_timestamp_header_errors_distinctly() {
        let cases: Vec<(String, VerifyError)> = vec![
            (
                String::new(),
                VerifyError::MalformedHeader {
                    header: TIMESTAMP_HEADER,
                    reason: "timestamp is not a valid RFC 3339 timestamp",
                },
            ),
            (
                "2021-03-25T05:09:27".to_string(),
                VerifyError::MalformedHeader {
                    header: TIMESTAMP_HEADER,
                    reason: "timestamp is not a valid RFC 3339 timestamp",
                },
            ),
            (
                "2021-03-25 05:09:27Z".to_string(),
                VerifyError::MalformedHeader {
                    header: TIMESTAMP_HEADER,
                    reason: "timestamp is not a valid RFC 3339 timestamp",
                },
            ),
            (
                "2021-02-29T05:09:27Z".to_string(),
                VerifyError::MalformedHeader {
                    header: TIMESTAMP_HEADER,
                    reason: "timestamp is not a valid RFC 3339 timestamp",
                },
            ),
            (
                "tampered".to_string(),
                VerifyError::MalformedHeader {
                    header: TIMESTAMP_HEADER,
                    reason: "timestamp is not a valid RFC 3339 timestamp",
                },
            ),
        ];
        for (value, expected) in cases {
            let result = verify_with(
                BODY,
                SIGNATURE,
                &value,
                clocked_at(1_616_648_967, Some(Duration::from_secs(300))),
            );
            assert_eq!(result, Err(expected), "input: {value:?}");
        }
    }
}
